### ISSUE TITLE
how to install obama in linux server

### ISSUE THREAD

**Issue by 1098994933** [rbouckaert/obama#1]
Is there a way of install obama in beast by command line rather than beastUi

**Comment by rbouckaert** [comment]
See section "install  by hand" in http://www.beast2.org/managing-packages/ .
In summary, 

* download the latest OBAMA package (currently https://github.com/rbouckaert/obama/releases/tag/v0.2.0).
* unzip in the OBAMA directory of the package directory for your operating system.
* delete `beauti.properties` file in the package directory.

The package directory is

* for Windows in Users\\\<YourName>\BEAST\2.X\
* for Mac in /Users/\<YourName>\/Library/Application Support/BEAST/2.X/
* for Linux /home/\<YourName>/.beast/2.X/

Here is \<YourName> the username you use, and in “2.X” the X refers to the major version of BEAST

**Comment by rbouckaert** [comment]
Forgot to say that OBAMA requires the bModelTest and BEASTLabs packages, so you need to install these as well.
